### ISSUE TITLE
 "run <step-count>" after prompt "Enter Option" ,  shows "Error" 

### ISSUE THREAD

**Issue by fantasy4everts** [joonspk-research/generative_agents#2]

**Comment by MiracleZeroPenguin** [comment]
I also encountered the same problem. Let me share my current solution.
I use traceback.print_exc() to trace the cause of the exception thrown at line 597 of `reverie.py`:
```
Traceback (most recent call last):
   File "**\reverie\backend_server\reverie.py", line 469, in open_server
     rs.start_server(int_count)
   File "**\reverie\backend_server\reverie.py", line 402, in start_server
     with open(curr_move_file, "w") as outfile:
FileNotFoundError: [Errno 2] No such file or directory: '../../environment/frontend_server/storage/test0808/movement/0.json'
```
In order to solve this error, I manually created the `movement folder` in the specified directory, and I was able to run the step successfully. I use `base_the_ville_isabella_maria_klaus` as forked simulation, and `test0808` is the name of the new simulation.

**Comment by joonspk-research** [comment]
+1 to MiracleZeroPenguin. Technically, the movement folder should be getting generated automatically as well (for some reason if it isn't, manually creating one should do the trick though).

**Comment by Gimel12** [comment]
Yes but when I create a folder inside the project, then when I start the simulation it said that the simulation name exist and it doesnt start again, can you guys update the source code so when we launch it it will create the movement folder properly. 

Thanks.

**Comment by wolfgangjblack** [comment]
This did not work for me - #https://github.com/joonspk-research/generative_agents/issues/5
